// Generated by https://quicktype.io

export interface CitaResponse {
    id:       string;
    fecha:    string;
    foto:     string;
    duracion: string;
    tamanio:  string;
    color:    string;
}


